"""Render bonsai/_params.py from the built extension's section registry.

Runs at build time, the way the nanobind stub does: the C++ registry is the
single source, read back through ``_bonsai._params_schema()``. The extension
is loaded straight from its shared-object file rather than through the
``bonsai`` package, because the package's ``__init__`` imports the very file
this script generates.

Usage::

    gen_params_py.py <package_dir> <output_path>

``<package_dir>`` is the build-tree ``bonsai/`` directory holding the built
``_bonsai`` extension.
"""

from __future__ import annotations

import glob
import importlib.util
import os
import sys

import numpy as np

HEADER = '''"""Typed parameter overrides, generated from the config section registry.

Generated by scripts/gen_params_py.py from ``_bonsai._params_schema()``;
do not edit. Every field defaults to ``None``, meaning "leave the library
default"; only set fields render into ``train()`` overrides. Behavior
(``to_pairs``/``from_dict``/``|`` merge) lives on the ``ParamsOps`` mixin.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar

from bonsai._params_ops import ParamsOps, SparseRepr

'''

PARAMS_DOC = '''    """Typed overrides over the library defaults, one field per config key.

    Unset (``None``) fields leave the library default, so a section names
    only what it changes. Renders to the same dotted-key pairs ``train()``
    always accepted; a TOML ``config=`` base composes underneath unchanged.

    Examples
    --------
    >>> p = Params(tree=Tree(max_depth=8), booster=Booster(n_iters=200))
    >>> bonsai.train(p, ds)                              # doctest: +SKIP
    >>> sweep = p | {"tree.max_depth": 10}               # dict-style merge
    """
'''


def _load_extension(package_dir: str):
    """Import the built ``_bonsai`` extension directly from its file."""
    matches = sorted(glob.glob(os.path.join(package_dir, "_bonsai.*")))
    ext = [p for p in matches if p.endswith((".so", ".pyd")) or ".cpython" in p]
    if not ext:
        raise SystemExit(f"no built _bonsai extension under {package_dir}")
    spec = importlib.util.spec_from_file_location("_bonsai", ext[0])
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _class_name(section: str) -> str:
    return "".join(part.capitalize() for part in section.split("_"))


def _shown_default(value, type_token: str) -> str:
    """The library default as the docstring shows it.

    Defaults come back as doubles widened from C++ floats, so a float is
    displayed at float32 precision (0.05, not 0.05000000074505806).
    """
    if type_token == "float":
        return str(np.float32(value))
    if type_token == "bool":
        return "true" if value else "false"
    return repr(value)


def render(schema) -> str:
    out = [HEADER]
    names = []
    for sec in schema:
        cls = _class_name(sec["section"])
        names.append((sec["section"], cls))
        out.append("@dataclass(frozen=True, repr=False)")
        out.append(f"class {cls}(SparseRepr):")
        out.append(f'    """[{sec["section"]}] overrides; None = library default.')
        out.append("")
        for f in sec["fields"]:
            shown = _shown_default(f["default"], f["type"])
            out.append(f"    {f['name']} : {f['type']}, default {shown}")
        out.append('    """')
        out.append("")
        for f in sec["fields"]:
            out.append(f"    {f['name']}: {f['type']} | None = None")
        out.append("")
        out.append("")
    out.append("@dataclass(frozen=True, repr=False)")
    out.append("class Params(ParamsOps):")
    out.append(PARAMS_DOC)
    for section, cls in names:
        out.append(f"    {section}: {cls} | None = None")
    out.append("")
    out.append("    _SECTION_TYPES: ClassVar[dict[str, type]] = {")
    for section, cls in names:
        out.append(f'        "{section}": {cls},')
    out.append("    }")
    out.append("")
    out.append("")
    all_names = ", ".join(f'"{cls}"' for _, cls in names)
    out.append(f'__all__ = ["Params", {all_names}]')
    out.append("")
    return "\n".join(out)


def main():
    package_dir, output_path = sys.argv[1], sys.argv[2]
    schema = _load_extension(package_dir)._params_schema()
    rendered = render(schema)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(rendered)


if __name__ == "__main__":
    main()
