"""Render docs/invariants.md from the tests that enforce the contracts.

A contract is worth writing down only if something fails when it breaks.
Prose cannot fail; a test can. So the enforced half of this page is
generated from the suite: a test that proves a contract carries a marker
comment naming it, and the claim lives in that comment, next to the
assertions that hold it true.

    // INVARIANT: levelwise-rejects-constraints
    // The levelwise grower rejects monotone and interaction constraints
    // at construction rather than silently ignoring them.
    TEST_CASE("ObliviousGrower: rejects constraints ...", "[...][invariant]")

Python tests use `# INVARIANT: <id>` above the `def`, same shape.

The residue is real and is not hidden: build flags, packaging matrices,
negative claims about nondeterminism, and decisions are all contracts no
unit test can hold. Those live hand-written in docs/invariants.src.md and
render into their own section, labelled asserted rather than enforced, so
a reader can tell at a glance which promises have a gate behind them.

    python3 scripts/render_invariants.py           # rewrite the page
    python3 scripts/render_invariants.py --check   # CI: fail on drift

Stdlib only, like the other doc generators; no build required.
"""

from __future__ import annotations

import pathlib
import re
import sys

from _render_common import write_or_check

REPO = pathlib.Path(__file__).resolve().parents[1]
OUT = REPO / "docs" / "invariants.md"
SRC = REPO / "docs" / "invariants.src.md"
TEST_DIRS = ("tests", "python/tests")

MARKER = re.compile(r"^\s*(?://|#)\s*INVARIANT:\s*(\S+)\s*$")
COMMENT = re.compile(r"^\s*(?://|#)\s?(.*)$")
CPP_CASE = re.compile(r'^\s*(?:TEMPLATE_(?:LIST_)?)?TEST_CASE\(\s*"([^"]+)"')
PY_DEF = re.compile(r"^\s*def\s+(test_\w+)")


def scan_tests() -> list[dict]:
    """Every marked contract, with the test that enforces it.

    Returns
    -------
    list[dict]
        One entry per marker: id, claim, test name, and source path.
    """
    found: list[dict] = []
    for d in TEST_DIRS:
        root = REPO / d
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("*")):
            if path.suffix not in (".cpp", ".hpp", ".py"):
                continue
            lines = path.read_text(errors="replace").splitlines()
            for i, line in enumerate(lines):
                m = MARKER.match(line)
                if not m:
                    continue
                claim: list[str] = []
                j = i + 1
                while j < len(lines) and COMMENT.match(lines[j]):
                    body = COMMENT.match(lines[j]).group(1).strip()
                    if body:
                        claim.append(body)
                    j += 1
                name = ""
                for k in range(j, min(j + 4, len(lines))):
                    hit = CPP_CASE.match(lines[k]) or PY_DEF.match(lines[k])
                    if hit:
                        name = hit.group(1)
                        break
                found.append({
                    "id": m.group(1),
                    "claim": " ".join(claim),
                    "test": name,
                    "path": path.relative_to(REPO).as_posix(),
                })
    return found


def render(entries: list[dict], residue: str) -> str:
    """The page: enforced contracts first, asserted ones after."""
    out = [
        "# Invariants",
        "",
        "The cross-file contracts. Each is stated once here and nowhere else;"
        " every other doc links to it rather than restating it.",
        "",
        "**Generated by `scripts/render_invariants.py`. Do not edit.**"
        " Enforced entries come from the tests that prove them, so a contract"
        " and its gate cannot drift apart; asserted entries are hand-written"
        " in `docs/invariants.src.md`.",
        "",
        "## Enforced by a test",
        "",
        "Breaking one of these fails the suite.",
        "",
    ]
    if not entries:
        out += ["_None marked yet._", ""]
    for e in sorted(entries, key=lambda x: x["id"]):
        out.append(f"### {e['id']}")
        out.append("")
        out.append(e["claim"])
        out.append("")
        # ../ so the repo-links hook rewrites it to a GitHub blob URL: the
        # target is source, not a documentation page.
        link = "../" + e["path"]
        where = f"[`{e['test']}`]({link})" if e["test"] else f"`{link}`"
        out.append(f"- enforced by: {where}")
        out.append("")
    out.append("## Asserted in prose")
    out.append("")
    out.append(
        "Two kinds sit here. Some cannot have a unit test: build flags,"
        " packaging matrices, claims about nondeterminism, decisions."
        " Others are testable and simply are not marked yet, which makes"
        " this section the backlog: promoting one is writing its test and"
        " adding the marker. The `code:` lines name the source carrying"
        " each claim, and docs-check fails when one stops resolving.")
    out.append("")
    out.append(residue.strip())
    out.append("")
    return "\n".join(out)


def main() -> int:
    """Render or check the page."""
    entries = scan_tests()
    residue = SRC.read_text() if SRC.exists() else ""
    return write_or_check(
        {OUT: render(entries, residue)},
        repo=REPO,
        script="scripts/render_invariants.py",
        label="invariants",
        detail=f"{len(entries)} enforced",
    )


if __name__ == "__main__":
    sys.exit(main())
