"""Render docs/use/make-map.md from the Makefile's `##` target comments.

Every public target documents itself with a `## description` on its rule
line, the self-documenting-Makefile convention:

    build: build/build.ninja  ## Configure and compile the CLI, library, ...

This generator reads those (target, description) pairs in file order and
writes the make-target map. Internal and file targets carry no `##` comment
and never match: pattern rules, path targets like `build/build.ninja`,
variable targets like `$(TOY_SENTINEL)`, and `.PHONY` all lack the comment,
and by convention a target whose name starts with a dot or underscore is
skipped even if it has one. So only the plain-named public commands appear.

    python3 scripts/render_make_map.py          # rewrite the page
    python3 scripts/render_make_map.py --check   # CI: fail on drift

Stdlib only, like the other doc generators; the CI check runs it with no
build. A public target with no `##` comment is invisible here, so document
new targets in the Makefile to have them show up.
"""

from __future__ import annotations

import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
MAKEFILE = REPO / "Makefile"
OUT = REPO / "docs" / "use" / "make-map.md"

# A rule line: target name, then anything, then `## description`. Recipe lines
# start with a tab and comment lines with `#`, so neither matches; path and
# variable targets start with a non-word character or contain `/` before the
# colon and fall out too.
TARGET_RE = re.compile(r"^([A-Za-z][A-Za-z0-9_.-]*):.*?##\s*(.+?)\s*$")

HEADER = """<!-- GENERATED by scripts/render_make_map.py from the Makefile's ## comments. Edit the Makefile, not this page. -->

# Make targets

Every make target you run day to day, generated from the `##` comments in the [Makefile](https://github.com/daniel-m-campos/bonsai/blob/main/Makefile). Add a `## description` to a target there and it appears here. `make help` prints a shorter version in the terminal.
"""


def targets() -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for line in MAKEFILE.read_text().splitlines():
        m = TARGET_RE.match(line)
        if not m:
            continue
        name, desc = m.group(1), m.group(2)
        if name.startswith((".", "_")):  # internal by convention
            continue
        out.append((name, desc))
    return out


def md_table(headers: list[str], rows: list[list[str]]) -> str:
    head = "| " + " | ".join(headers) + " |"
    sep = "|" + "|".join("---" for _ in headers) + "|"
    body = ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join([head, sep, *body])


def render() -> str:
    rows = [[f"`make {name}`", desc] for name, desc in targets()]
    return HEADER + "\n" + md_table(["target", "what it does"], rows) + "\n"


def main() -> int:
    rows = targets()
    if not rows:
        print("ERROR: no `## ` target comments found in the Makefile; "
              "the map would be empty.", file=sys.stderr)
        return 1
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("ERROR: docs/use/make-map.md is stale; run "
                  "python3 scripts/render_make_map.py", file=sys.stderr)
            return 1
        print(f"make-target map: in sync ({len(rows)} targets)")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(REPO)} ({len(rows)} targets)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
