#!/usr/bin/env python3
"""Rebuild the n/p, selection-trust, and pipeline-race summary tables from the
raw jsonl rows into one markdown report.

    python3 scripts/render_np_report.py   # writes benchmarks/np-studies-report-2026-07.md

Stdlib only. Every number in the report is recomputed from
benchmarks/results/*.jsonl, so the report cannot drift from the data.
"""
import json
import pathlib
import statistics as st
from collections import defaultdict

REPO = pathlib.Path(__file__).resolve().parents[1]
RESULTS = REPO / "benchmarks" / "results"
OUT = REPO / "benchmarks" / "np-studies-report-2026-07.md"


def load(name):
    return [json.loads(x) for x in (RESULTS / name).read_text().splitlines() if x.strip()]


def table(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("--" for _ in headers) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


sections = ["# The n/p studies: raw-data-derived tables (2026-07)",
            "",
            "Generated by `scripts/render_np_report.py` from the jsonl rows in "
            "`benchmarks/results/`. Context, design, and pre-registered "
            "predictions live in `scripts/probe_np_crossover.py` and the "
            "session discussion. These studies are deliberately unmerged; "
            "this branch is their home.", ""]

# ---- study 1: crossover + scale ---------------------------------------------
rows = load("np-crossover-2026-07.jsonl")
cells = defaultdict(dict)
for r in rows:
    if r["dataset"] in ("superconductivity", "QSAR-TID-11"):
        cells[(r["dataset"], r["n_train"], r["draw"])][r["arm"]] = r
sections.append("## Study 1a: row-count crossover (real data, injected noise)")
sections.append("")
sections.append("Delta = arm holdout rmse minus keep-everything baseline; negative wins. "
                "`nk` = shuffled-copy noise features kept in the top-81 (superconductivity).")
sections.append("")
body = []
for ds in ("superconductivity", "QSAR-TID-11"):
    for n in sorted({k[1] for k in cells if k[0] == ds}, reverse=True):
        draws = [v for k, v in cells.items() if k[0] == ds and k[1] == n]
        row = [ds, n, f"{st.mean(d['baseline']['error'] for d in draws):.3f}"]
        for arm in ("oracle", "gain_topk", "shap_val_topk"):
            if arm in draws[0]:
                dl = st.mean(d[arm]["error"] - d["baseline"]["error"] for d in draws)
                nk = st.mean(d[arm]["noise_kept"] for d in draws)
                row.append(f"{dl:+.3f}" + (f" (nk {nk:.0f})" if nk >= 0 else ""))
            else:
                row.append("-")
        body.append(row)
sections.append(table(["dataset", "n train", "baseline rmse", "oracle",
                       "gain top-k", "shap_val top-k"], body))
sections.append("")
scale = [r for r in rows if r["dataset"] == "synthetic"]
if scale:
    sections.append("## Study 1b: GPU scale check (3.2M x 2,048, 64 informative, L40S)")
    sections.append("")
    sections.append(table(["arm", "holdout rmse", "fit wall s", "noise kept"],
                          [[r["arm"], r["error"], r["fit_wall_s"],
                            r["noise_kept"] if r["noise_kept"] >= 0 else "-"]
                           for r in scale]))
    sections.append("")

# ---- study 2: trust map ------------------------------------------------------
rows = load("hft-selection-trust-2026-07.jsonl") + load("hft-selection-trust-ext-2026-07.jsonl")
cells = defaultdict(dict)
for r in rows:
    cells[(r["r2_target"], r["H"], r["lam"], r["draw"])][r["arm"]] = r
R2S = sorted({k[0] for k in cells}, reverse=True)


def mcell(r2t, H, lam, arm, f):
    return st.mean(cells[(r2t, H, lam, d)][arm][f] for d in (0, 1))


sections.append("## Study 2: the trust map (markout-shaped synthetic, k=32 of 128)")
sections.append("")
sections.append("Cell = junk kept in top 32 by the gain ranking / strongest-10 "
                "true signals found. H = markout overlap width; effective "
                "sample is roughly 140k/H.")
for lam, tag in ((1.0, "fixed relationships"), (0.7, "drifting relationships")):
    sections.append("")
    sections.append(f"### {tag}")
    sections.append("")
    body = []
    for r2t in R2S:
        row = [f"{r2t*100:g}%"]
        for H in (1, 20, 100):
            row.append(f"{mcell(r2t, H, lam, 'gain_topk', 'noise_kept'):.1f} junk, "
                       f"{mcell(r2t, H, lam, 'gain_topk', 'sig_strong'):.1f}/10")
        body.append(row)
    sections.append(table(["signal", "H=1", "H=20", "H=100"], body))
sections.append("")
sections.append("### era-averaged ranking under drift (same cells)")
sections.append("")
body = []
for r2t in R2S:
    row = [f"{r2t*100:g}%"]
    for H in (1, 20, 100):
        row.append(f"{mcell(r2t, H, 0.7, 'era_stability_topk', 'noise_kept'):.1f} junk, "
                   f"{mcell(r2t, H, 0.7, 'era_stability_topk', 'sig_strong'):.1f}/10")
    body.append(row)
sections.append(table(["signal", "H=1", "H=20", "H=100"], body))
sections.append("")

# ---- study 3: pipeline race --------------------------------------------------
rows = load("pipeline-race-2026-07.jsonl")
cells = defaultdict(dict)
for r in rows:
    cells[(r["r2_target"], r["H"], r["lam"], r["draw"])][r["arm"]] = r
ARMS = ["corr_filter", "naive_gain", "naive_shap", "era_only",
        "pipe_no_era", "pipe_no_drift", "pipe_full", "oracle", "baseline"]
sections.append("## Study 3: pipeline race (200 features: 24 signal clusters, "
                "16 drift-broken, 88 noise; k=24)")
for lam, tag in ((1.0, "fixed relationships"), (0.7, "drifting relationships")):
    sections.append("")
    sections.append(f"### composition, {tag} (mean over 12 cells)")
    sections.append("")
    keys = [k for k in cells if k[2] == lam]
    body = []
    for arm in ARMS:
        body.append([arm,
                     f"{st.mean(cells[k][arm]['clusters_covered'] for k in keys):.1f}",
                     f"{st.mean(cells[k][arm]['dup_slots'] for k in keys):.1f}",
                     f"{st.mean(cells[k][arm]['broken_kept'] for k in keys):.1f}",
                     f"{st.mean(cells[k][arm]['noise_kept'] for k in keys):.1f}"])
    sections.append(table(["arm", "groups/24", "dup slots", "broken kept",
                           "noise kept"], body))
    sections.append("")
    sections.append(f"### holdout r2 x100 by condition, {tag} (mean of 2 draws)")
    sections.append("")
    body = []
    for r2t in (0.25, 0.10, 0.05):
        for H in (1, 20):
            row = [f"{int(r2t*100)}% H={H}"]
            for arm in ARMS:
                v = st.mean(cells[(r2t, H, lam, d)][arm]["r2_hold"] for d in (0, 1))
                row.append(f"{100*v:.2f}")
            body.append(row)
    sections.append(table(["condition", *ARMS], body))
sections.append("")
sections.append("Caveats carried from the discussion: 2 draws per cell; drift "
                "cells have large draw-to-draw spread (judge policies by their "
                "bad draw, not the mean); the r2-share ratio metric was "
                "retired mid-analysis (ratio averaging with small denominators "
                "misleads); the first pipeline run had a clustering index bug, "
                "caught by the impossible duplicate count and rerun.")
OUT.write_text("\n".join(sections) + "\n")
print(f"wrote {OUT.relative_to(REPO)} ({len(sections)} blocks)")
