"""Render docs/learn/timeline.md from the committed docs/learn/timeline.json.

The timeline is a hand-maintained history of gradient-boosted-tree ideas: one
entry per milestone with its year, the idea in a line, an attribution, a link
to the paper, which libraries carry it, and where bonsai stands on it. The
data is the source of truth; this generator only shapes it into a page.

    python3 scripts/render_timeline.py           # rewrite the page
    python3 scripts/render_timeline.py --check    # CI: fail on drift

Stdlib only, like the other doc generators; the CI check runs it with no
build. Two drift gates fire before the page is written, so a broken data file
fails loudly instead of shipping:

  1. Schema: every entry carries the required keys, a known bonsai_status, and
     adopters drawn from the four tracked libraries.
  2. Links: every bonsai_link resolves. The file part must exist under docs/,
     and any #anchor must match a heading in that file, slugified the way
     MkDocs (python-markdown's toc) slugifies headings. So a renamed decision
     heading or a moved guide chapter fails the check.

Add or edit a milestone in docs/learn/timeline.json, then rerun this script.
"""

from __future__ import annotations

import json
import pathlib
import re
import sys
import unicodedata

REPO = pathlib.Path(__file__).resolve().parents[1]
DOCS = REPO / "docs"
SRC = DOCS / "learn" / "timeline.json"
OUT = DOCS / "learn" / "timeline.md"

STATUSES = ("adopted", "adapted", "declined", "tbd", "origin")

# Library key -> display name. bonsai stays lowercase (STYLE.md); the three
# reference libraries capitalize in prose.
DISPLAY = {
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "catboost": "CatBoost",
    "bonsai": "bonsai",
}

STATUS_LEGEND = {
    "adopted": "bonsai implements the idea.",
    "adapted": "bonsai carries the idea in a changed form.",
    "declined": "Measured or judged not worth the complexity, for now.",
    "tbd": "A named future campaign, not yet built.",
    "origin": "First done in bonsai.",
}

REQUIRED_KEYS = (
    "year", "title", "idea", "attribution",
    "link", "adopters", "bonsai_status", "bonsai_link",
)

HEADER = """<!-- GENERATED by scripts/render_timeline.py from docs/learn/timeline.json. Edit the data file or the generator, not this page. -->

# How we got here

Gradient-boosted trees are the sum of forty years of small, sharp ideas. This page traces that lineage and marks where bonsai stands on each idea: adopted, adapted, declined, still open, or first done here.

This page supersedes the archived library notes for [XGBoost](../lineage/xgboost.md), [LightGBM](../lineage/lightgbm.md), and [CatBoost](../lineage/catboost.md).

The diagram sketches the timeline. The table below carries the detail, one row per idea. Each row links into the guide, the decisions log, or a design note for how bonsai handles that idea.
"""

FOOTER = """## About this page

The diagram and the table are generated from `docs/learn/timeline.json` by `scripts/render_timeline.py`, and CI fails on drift. Edit the data, not this page.
"""


# ---- slugify (mirrors python-markdown's toc, which MkDocs uses) --------------

def slugify(text: str) -> str:
    value = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    value = re.sub(r"`", "", value)  # heading code spans render as plain text
    value = re.sub(r"[^\w\s-]", "", value).strip().lower()
    return re.sub(r"[-\s]+", "-", value)


def heading_slugs(md_path: pathlib.Path) -> set[str]:
    slugs: set[str] = set()
    in_code = False
    for line in md_path.read_text().splitlines():
        if re.match(r"^\s*(```|~~~)", line):
            in_code = not in_code
            continue
        if in_code:
            continue
        m = re.match(r"^(#{1,6})\s+(.*?)\s*$", line)
        if m:
            slugs.add(slugify(m.group(2)))
    return slugs


# ---- validation --------------------------------------------------------------

def schema_errors(entries: list[dict]) -> list[str]:
    problems: list[str] = []
    for i, e in enumerate(entries):
        where = f"entry {i} ({e.get('title', '?')})"
        missing = [k for k in REQUIRED_KEYS if k not in e]
        if missing:
            problems.append(f"{where}: missing keys {missing}")
            continue
        if e["bonsai_status"] not in STATUSES:
            problems.append(
                f"{where}: bonsai_status {e['bonsai_status']!r} not in {STATUSES}")
        bad = [a for a in e["adopters"] if a not in DISPLAY]
        if bad:
            problems.append(f"{where}: unknown adopters {bad}; known: {list(DISPLAY)}")
        if not isinstance(e["year"], int):
            problems.append(f"{where}: year must be an integer")
    return problems


def link_errors(entries: list[dict]) -> list[str]:
    problems: list[str] = []
    for e in entries:
        link = e.get("bonsai_link", "")
        path_part, _, anchor = link.partition("#")
        target = (OUT.parent / path_part).resolve()
        if not target.is_file():
            problems.append(
                f"{e.get('title', '?')}: bonsai_link file not found: {path_part}")
            continue
        if anchor and anchor not in heading_slugs(target):
            problems.append(
                f"{e.get('title', '?')}: anchor #{anchor} not a heading in "
                f"{path_part} (valid: {sorted(heading_slugs(target))})")
    return problems


# ---- rendering ---------------------------------------------------------------

def load() -> tuple[str, list[dict]]:
    data = json.loads(SRC.read_text())
    entries = sorted(data["milestones"], key=lambda e: (e["year"], data["milestones"].index(e)))
    return data.get("title", "The lineage"), entries


def decade(year: int) -> str:
    return f"{year // 10 * 10}s"


def mermaid(title: str, entries: list[dict]) -> str:
    lines = ["```mermaid", "timeline", f"    title {title}"]
    current_decade = None
    current_year = None
    for e in entries:
        dec = decade(e["year"])
        if dec != current_decade:
            lines.append(f"    section {dec}")
            current_decade = dec
            current_year = None
        if e["year"] != current_year:
            lines.append(f"        {e['year']} : {e['title']}")
            current_year = e["year"]
        else:
            lines[-1] += f" : {e['title']}"
    lines.append("```")
    return "\n".join(lines)


def carried_by(adopters: list[str]) -> str:
    if not adopters:
        return "none"
    return ", ".join(DISPLAY[a] for a in adopters)


def idea_cell(e: dict) -> str:
    title = f"[{e['title']}]({e['link']})" if e["link"] else e["title"]
    return f"**{title}**: {e['idea']} *({e['attribution']})*"


def md_table(headers: list[str], rows: list[list[str]]) -> str:
    head = "| " + " | ".join(headers) + " |"
    sep = "|" + "|".join("---" for _ in headers) + "|"
    body = ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join([head, sep, *body])


def render() -> str:
    title, entries = load()
    rows = [
        [str(e["year"]), idea_cell(e), carried_by(e["adopters"]),
         f"[{e['bonsai_status']}]({e['bonsai_link']})"]
        for e in entries
    ]
    table = md_table(["Year", "Idea", "Carried by", "bonsai"], rows)
    legend = md_table(
        ["Status", "Meaning"],
        [[f"`{s}`", STATUS_LEGEND[s]] for s in STATUSES])
    parts = [
        HEADER,
        mermaid(title, entries) + "\n",
        "## The milestones\n\n" + table + "\n",
        "## Status legend\n\n" + legend + "\n",
        FOOTER,
    ]
    return "\n".join(parts)


def main() -> int:
    _, entries = load()
    problems = schema_errors(entries)
    problems += link_errors(entries) if not problems else []
    if problems:
        print("ERROR: timeline data invalid:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1
    text = render()
    n = len(entries)
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("ERROR: docs/learn/timeline.md is stale; run "
                  "python3 scripts/render_timeline.py", file=sys.stderr)
            return 1
        print(f"timeline: in sync ({n} milestones)")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(REPO)} ({n} milestones)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
